### ISSUE TITLE
Proposal for new design

### ISSUE THREAD

**Issue by pragmaticivan** [hexpm/hexdocs-static#10]
<img width="1127" alt="screen shot 2018-04-14 at 1 46 54 pm" src="https://user-images.githubusercontent.com/301291/38772394-65427b96-3fea-11e8-8a1c-ffb1f7a147e4.png">

<img width="1123" alt="screen shot 2018-04-14 at 1 47 02 pm" src="https://user-images.githubusercontent.com/301291/38772393-65250cd2-3fea-11e8-9e3d-7808857c67ee.png">

**Comment by ericmj** [comment]
Definitely an improvement over the current design. 👍

**Comment by wojtekmach** [comment]
Looks great! The only minor nitpick is I'd drop "Center" from "HexDocs Center" :)

**Comment by pragmaticivan** [comment]
@wojtekmach I was thinking about that but did some research on different projects, and it was the pattern I found for that type of project, I can drop it though.

**Comment by ericmj** [comment]
I agree with @wojtekmach, I also prefer just "HexDocs". Would love a PR for this 😄

**Comment by wojtekmach** [comment]
@pragmaticivan Ping :D

**Comment by wojtekmach** [comment]
We're working on a hex.pm redesign so after that is done, we'd likely do a redesign of hexdocs.pm in a similar style.
