### ISSUE TITLE
Documentation search on hexdocs.pm

### ISSUE THREAD

**Issue by amolenaar** [hexpm/hexdocs-static#6]
Currently it more or less requires Google to search hexdocs.pm. Or hex.pm.

I'd like to be able to search for modules and module documentation from the main page of hexdocs.pm. This would make the hexdocs.pm landing page a lot more useful.

A small search script based on the contents of `sitemap.xml` would probably do, for starters. At a later stage we can differentiate on version.

I'd be happy to create a PR if you'd like this functionality incorporated.

**Comment by ericmj** [comment]
The idea is that if you want to search for packages by names, and don't want to use Google, that you should go through hex.pm.

But it doesn't hurt to have search on hexdocs.pm as well so if you want to work on it please go ahead. For more advanced search I think a different approach than sitemap.xml is needed.

**Comment by amolenaar** [comment]
I agree wrt the advanced search. Let's start with something simple first :).

**Comment by ericmj** [comment]
Closed in #7. We are still open for ideas about more advanced search.
